### ISSUE TITLE
Push refused

### ISSUE THREAD

**Issue by newaeonweb** [LokeCarlsson/awesome-gridsome#3]
Hello, i tried to push a new branch to make a pull-request but receive the following error:
`ERROR: Permission to LokeCarlsson/awesome-gridsome.git denied to newaeonweb.`

Any help?
Thanks in advance

**Comment by LokeCarlsson** [comment]
Try creating a fork which you push to, then you can create a pull request from that.

**Comment by newaeonweb** [comment]
@LokeCarlsson Hi. It's work now. Thanks!!

**Comment by LokeCarlsson** [comment]
@newaeonweb Perfect 😃
