### ISSUE TITLE
Add more links and resources

### ISSUE THREAD

**Issue by LokeCarlsson** [LokeCarlsson/awesome-gridsome#9]
Starter project are great additions to this list.

**Comment by chetanraj** [comment]
i'll add [https://medium.com/jsessentials/how-gridsome-works-with-github-pages-aeacaf6f3622](this)

**Comment by chetanraj** [comment]
In which section shall I add this ?

**Comment by LokeCarlsson** [comment]
Great! I would say under `Tutorials`, but if you feel like a section is missing, we can always extend the sections as it grows.

**Comment by CharaeKeow** [comment]
I would like  to work on this.

**Comment by CharaeKeow** [comment]
@LokeCarlsson What do you think about adding tutorial posted exclusively for Medium members? Like [this one](https://levelup.gitconnected.com/how-to-build-an-awesome-website-with-gridsome-and-markdown-files-8f5422bb0183).

**Comment by LokeCarlsson** [comment]
@CharaeKeow I can't see any paywall, are you sure that post is locked down?

**Comment by LokeCarlsson** [comment]
Ah you mean like that. I don't hang around medium much because of these things. I think it's good to keep medium posts to a minimum. A open framework should definitely have open resources.
